%-----------------------------------------------------------------------
%    software    :   DotX Wind Turbine Control Software
%    author      :   DotX Control Solutions BV
%                    1817DC Alkmaar, Netherlands
%                    www.dotxcontrol.com
%                    info@dotxcontrol.com
%-----------------------------------------------------------------------

master = loadlist();

VERSION = 'DWTC[2.0.0]';

MEASUREMENTS = { 
    'OPER_MEAS_GENSPEED' , ...
    'OPER_MEAS_AZIMUTH'  , ...
    'OPER_MEAS_FAACC'    , ...
    'OPER_MEAS_SWACC'    , ...
    'OPER_MEAS_GENTORQUE', ...
    'OPER_MEAS_TIME'     , ...
    'OPER_MEAS_ELECPOWER', ...
    'OPER_MEAS_YAWERROR' , ...
    'OPER_MEAS_TIMESTEP' , ...
    'OPER_MEAS_GRIDCONT' , ...
    'OPER_MEAS_BENMOM1'  , ...
    'OPER_MEAS_BENMOM2'  , ...
    'OPER_MEAS_BENMOM3'  , ...
    'OPER_MEAS_PITCH1'   , ...
    'OPER_MEAS_PITCH2'   , ...
    'OPER_MEAS_PITCH3'   , ...
    'OPER_MEAS_ACTTYPE'  , ...
    'OPER_MEAS_HUBWIND'    ...
} ;

DEMAND = {
    'OPER_DEM_GENTORQUE' , ...
    'OPER_DEM_PITCH1'    , ...
    'OPER_DEM_PITCH2'    , ...
    'OPER_DEM_PITCH3'    , ...
    'OPER_DEM_YAWRATE'     ...
} ;

ROTORSPEED_POWER = {
    'BASE_SPD_RTSP'             , ...
    'BASE_SPD_RTSP_P_HPF'       , ...
    'BASE_SPD_RTSP_P_NFP'       , ...
    'BASE_SPD_RTSP_P_NFF'       , ...
    'BASE_SPD_RTSP_P_LPF'       , ...
    'BASE_SPD_RTSP_T_HPF'       , ...
    'BASE_SPD_RTSP_T_NFP'       , ...
    'BASE_SPD_RTSP_T_NFF'       , ...
    'BASE_SPD_RTSP_T_LPF'       , ...
    'BASE_SPD_TORQ_MIN'         , ...
    'BASE_SPD_TORQ_MAX'         , ...
    'BASE_SPD_TORQ_SETPOINT'    , ...
    'BASE_SPD_PIT_MIN'          , ...
    'BASE_SPD_PIT_MAX'          , ...
    'BASE_SPD_PIT_MIN_SPD'      , ...
    'BASE_SPD_PIT_MAX_SPD'      , ...
    'BASE_SPD_PIT_SETPOINT'     , ...
    'BASE_SPD_DEM_TORQ'         , ...
    'BASE_SPD_DEM_PITCH'          ...
} ;

DRIVETRAINDAMPING = {
    'BASE_DTD_OMR'              , ...
    'BASE_DTD_OMR_HPF'          , ...  
    'BASE_DTD_OMR_NFP'          , ...
    'BASE_DTD_OMR_NFF'          , ...
    'BASE_DTD_OMR_LPF'          , ...
    'BASE_DTD_DEM_TORQ'         , ...
    'BASE_DTD_DEM_TORQ_FILT'      ...
} ;

SIDEWARDSDAMPING = {
    'BASE_SWD_SIDEWACC'         , ...
    'BASE_SWD_SIDEWACC_HPF'     , ...
    'BASE_SWD_SIDEWACC_NFP'     , ...
    'BASE_SWD_SIDEWACC_NFF'     , ...
    'BASE_SWD_SIDEWACC_LPF'     , ...
    'BASE_SWD_DEM_TORQ'           ...
} ;

FOREAFTDAMPING = {
    'BASE_FAD_FOREAFTACC'       , ...
    'BASE_FAD_FOREAFTACC_HPF'   , ...
    'BASE_FAD_FOREAFTACC_NFP'   , ...
    'BASE_FAD_FOREAFTACC_NFF'   , ...
    'BASE_FAD_FOREAFTACC_LPF'   , ...
    'BASE_FAD_MIN'              , ...
    'BASE_FAD_MAX'              , ...
    'BASE_FAD_MIN_SPD'          , ...
    'BASE_FAD_MAX_SPD'          , ...
    'BASE_FAD_DEM_PIT'          , ...
} ;

IPC0P = {
    'BASE_IPC0P_ERD'            , ...
    'BASE_IPC0P_ERD_HPF'        , ...
    'BASE_IPC0P_ERD_NFP'        , ...
    'BASE_IPC0P_ERD_NFF'        , ...
    'BASE_IPC0P_ERD_LPF'        , ...
    'BASE_IPC0P_ERQ'            , ...
    'BASE_IPC0P_ERQ_HPF'        , ...
    'BASE_IPC0P_ERQ_NFP'        , ...
    'BASE_IPC0P_ERQ_NFF'        , ...
    'BASE_IPC0P_ERQ_LPF'        , ...
    'BASE_IPC0P_D_MIN'          , ...
    'BASE_IPC0P_D_MAX'          , ...
    'BASE_IPC0P_D_DEM_PIT'      , ...
    'BASE_IPC0P_Q_MIN'          , ...
    'BASE_IPC0P_Q_MAX'          , ...
    'BASE_IPC0P_Q_DEM_PIT'      , ...
    'BASE_IPC0P_DEM_PIT1'       , ...
    'BASE_IPC0P_DEM_PIT2'       , ...
    'BASE_IPC0P_DEM_PIT3'         ...
} ;

IPC1P = {
    'BASE_IPC1P_ERD'            , ...
    'BASE_IPC1P_ERD_HPF'        , ...
    'BASE_IPC1P_ERD_NFP'        , ...
    'BASE_IPC1P_ERD_NFF'        , ...
    'BASE_IPC1P_ERD_LPF'        , ...
    'BASE_IPC1P_ERQ'            , ...
    'BASE_IPC1P_ERQ_HPF'        , ...
    'BASE_IPC1P_ERQ_NFP'        , ...
    'BASE_IPC1P_ERQ_NFF'        , ...
    'BASE_IPC1P_ERQ_LPF'        , ...
    'BASE_IPC1P_D_MIN'          , ...
    'BASE_IPC1P_D_MAX'          , ...
    'BASE_IPC1P_D_DEM_PIT'      , ...
    'BASE_IPC1P_Q_MIN'          , ...
    'BASE_IPC1P_Q_MAX'          , ...
    'BASE_IPC1P_Q_DEM_PIT'      , ...
    'BASE_IPC1P_DEM_PIT1'       , ...
    'BASE_IPC1P_DEM_PIT2'       , ...
    'BASE_IPC1P_DEM_PIT3'         ...
} ; 

IPC2P = {
    'BASE_IPC2P_ERD'            , ...
    'BASE_IPC2P_ERD_HPF'        , ...
    'BASE_IPC2P_ERD_NFP'        , ...
    'BASE_IPC2P_ERD_NFF'        , ...
    'BASE_IPC2P_ERD_LPF'        , ...
    'BASE_IPC2P_ERQ'            , ...
    'BASE_IPC2P_ERQ_HPF'        , ...
    'BASE_IPC2P_ERQ_NFP'        , ...
    'BASE_IPC2P_ERQ_NFF'        , ...
    'BASE_IPC2P_ERQ_LPF'        , ...
    'BASE_IPC2P_D_MIN'          , ...
    'BASE_IPC2P_D_MAX'          , ...
    'BASE_IPC2P_D_DEM_PIT'      , ...
    'BASE_IPC2P_Q_MIN'          , ...
    'BASE_IPC2P_Q_MAX'          , ...
    'BASE_IPC2P_Q_DEM_PIT'      , ...
    'BASE_IPC2P_DEM_PIT1'       , ...
    'BASE_IPC2P_DEM_PIT2'       , ...
    'BASE_IPC2P_DEM_PIT3'         ...   
} ;

IPC3P = {
    'BASE_IPC3P_ERD'            , ...
    'BASE_IPC3P_ERD_HPF'        , ...
    'BASE_IPC3P_ERD_NFP'        , ...
    'BASE_IPC3P_ERD_NFF'        , ...
    'BASE_IPC3P_ERD_LPF'        , ...
    'BASE_IPC3P_ERQ'            , ...
    'BASE_IPC3P_ERQ_HPF'        , ...
    'BASE_IPC3P_ERQ_NFP'        , ...
    'BASE_IPC3P_ERQ_NFF'        , ...
    'BASE_IPC3P_ERQ_LPF'        , ...
    'BASE_IPC3P_D_MIN'          , ...
    'BASE_IPC3P_D_MAX'          , ...
    'BASE_IPC3P_D_DEM_PIT'      , ...
    'BASE_IPC3P_Q_MIN'          , ...
    'BASE_IPC3P_Q_MAX'          , ...
    'BASE_IPC3P_Q_DEM_PIT'      , ...
    'BASE_IPC3P_DEM_PIT1'       , ...
    'BASE_IPC3P_DEM_PIT2'       , ...
    'BASE_IPC3P_DEM_PIT3'         ...   
} ;

PITFOLLOW = {    
    'BASE_PITFOLLOW_ERR1'       , ...    
    'BASE_PITFOLLOW_ERR2'       , ...    
    'BASE_PITFOLLOW_ERR3'       , ...   
    'BASE_PITFOLLOW_DEM_PIT1'   , ...    
    'BASE_PITFOLLOW_DEM_PIT2'   , ...    
    'BASE_PITFOLLOW_DEM_PIT3'     ...    
} ;

YAWCONTROL = {   
    'BASE_YAWMOT_ERR'           , ... 
    'BASE_YAWMOT_ERR_LPF'       , ... 
    'BASE_YAWMOT_ACTIVE'        , ... 
    'BASE_YAW_SETPOINT'         , ...   
    'BASE_YAW_DEMYAWRATE'         ... 
} ;
   
DNPC = { 
    'DNPC_TIME_MEAS'            , ...
    'DNPC_GENSPEED_MEAS'        , ...
    'DNPC_GENTORQUE_MEAS'       , ...
    'DNPC_HUBWIND_MEAS'         , ...
    'DNPC_AZIMUTH_MEAS'         , ...
    'DNPC_SWARDSACC_MEAS'       , ...
    'DNPC_FORAFTACC_MEAS'       , ...
    'DNPC_POWER_MEAS'           , ...
    'DNPC_BENMOM1_MEAS'         , ...
    'DNPC_BENMOM2_MEAS'         , ...
    'DNPC_BENMOM3_MEAS'         , ...
    'DNPC_PITCH1_MEAS'          , ...
    'DNPC_PITCH2_MEAS'          , ...
    'DNPC_PITCH3_MEAS'          , ...
    'DNPC_VAXEST_OBS'           , ...
    'DNPC_VAXEST1_OBS'          , ...
    'DNPC_VAXEST2_OBS'          , ...
    'DNPC_VAXEST3_OBS'          , ...
    'DNPC_XFAEST_OBS'           , ...
    'DNPC_VFAEST_OBS'           , ...
    'DNPC_PITCH1_OBS'           , ...
    'DNPC_PITCH2_OBS'           , ...
    'DNPC_PITCH3_OBS'           , ...
    'DNPC_GENSPEED_OPNL'        , ...
    'DNPC_GENTORQUE_OPNL'       , ...
    'DNPC_POWER_OPNL'           , ...
    'DNPC_FOREAFTACC_OPNL'      , ...
    'DNPC_XFAEST_OPNL'          , ...
    'DNPC_VFAEST_OPNL'          , ...
    'DNPC_BENMOM1_OPNL'         , ...
    'DNPC_BENMOM2_OPNL'         , ...
    'DNPC_BENMOM3_OPNL'         , ...
    'DNPC_GENSPEED_FILT'        , ...
    'DNPC_GENTORQUE_FILT'       , ...
    'DNPC_POWER_FILT'           , ...
    'DNPC_XFAEST_FILT'          , ...
    'DNPC_VFAEST_FILT'          , ...
    'DNPC_VAXEST_FILT'          , ...
    'DNPC_VAXEST1_FILT'         , ...
    'DNPC_VAXEST2_FILT'         , ...
    'DNPC_VAXEST3_FILT'         , ...
    'DNPC_BENMOM1_FILT'         , ...
    'DNPC_BENMOM2_FILT'         , ...
    'DNPC_BENMOM3_FILT'         , ...
    'DNPC_GENSPEED_SETP'        , ...
    'DNPC_POWER_SETP'           , ...
    'DNPC_GENTORQUE_SETP'       , ...
    'DNPC_PITCH1_SETP'          , ...
    'DNPC_PITCH2_SETP'          , ...
    'DNPC_PITCH3_SETP'          , ...
    'DNPC_GENTORQUE_DEM'        , ...
    'DNPC_PITCH1_DEM'           , ...
    'DNPC_PITCH2_DEM'           , ...
    'DNPC_PITCH3_DEM'           , ...
    'DNPC_COMPEN_OM'            , ...
    'DNPC_COMPEN_KC'              ...
} ;
    
EXTREMEEVENT = {
    'EEC_TIME'                  , ...
    'EEC_HUBWIND'               , ...
    'EEC_HUBWIND_F'             , ...
    'EEC_TGEN'                  , ...
    'EEC_TGEN_F'                , ...
    'EEC_OMGR'                  , ...
    'EEC_OMGR_F'                , ...
    'EEC_PITCH'                 , ...
    'EEC_PITCH_F'               , ...
    'EEC_PITCH1'                , ...
    'EEC_PITCH1_F'              , ...
    'EEC_PITCH2'                , ...
    'EEC_PITCH2_F'              , ...
    'EEC_MB1'                   , ...
    'EEC_MB1_F'                 , ...
    'EEC_MB2'                   , ...
    'EEC_MB2_F'                 , ...
    'EEC_PITCH3'                , ...
    'EEC_PITCH3_F'              , ...
    'EEC_MB3'                   , ...
    'EEC_MB3_F'                 , ...
    'EEC_EST_WIND'              , ...
    'EEC_EST_WIND_F'            , ...
    'EEC_EST_OMGR'              , ...
    'EEC_ECG_LSFIT'             , ...
    'EEC_ECG_LSFITRES'          , ...
    'EEC_ECG_LEVEL'             , ...
    'EEC_ECG_FLAG'              , ...
    'EEC_EOG_LSFIT'             , ...
    'EEC_EOG_LSFITRES'          , ...
    'EEC_EOG_LEVEL'             , ...
    'EEC_EOG_FLAG'              , ...
    'EEC_EOG50_LSFIT'           , ...
    'EEC_EOG50_LSFITRES'        , ...
    'EEC_EOG50_LEVEL'           , ...
    'EEC_EOG50_FLAG'              ...
} ;

SUPERVISORY = {
    'SUP_TRIGGER'               , ...    
    'SUP_TRIGGER_INDEX'         , ...    
    'SUP_STATE'                 , ...    
    'SUP_STATE_INDEX'             ...
} ;

% Assemble list
    list = {};
    list = horzcat( list , MEASUREMENTS         );
    list = horzcat( list , DEMAND               );
    list = horzcat( list , ROTORSPEED_POWER     );
%    list = horzcat( list , DRIVETRAINDAMPING    );
    list = horzcat( list , SIDEWARDSDAMPING     );
    list = horzcat( list , FOREAFTDAMPING       );
%    list = horzcat( list , IPC0P                );
    list = horzcat( list , IPC1P                );
    list = horzcat( list , IPC2P                );
%    list = horzcat( list , IPC3P                );
%    list = horzcat( list , PITFOLLOW            );
%    list = horzcat( list , YAWCONTROL           );
%    list = horzcat( list , DNPC                 );
%    list = horzcat( list , EXTREMEEVENT         );
    list = horzcat( list , SUPERVISORY          );

% Write the GUI inputfile
fid = fopen( './../../interface/DotXGUIConfig.ini', 'w' );
fprintf( fid, '[signals]\n');
for k = 1:length(list)
    found = 0;
    for j = 1:length(master)
        if strcmp( list{k} , master{j} )
            found = 1;
            fprintf(fid, '%s=%d \n', list{k}, j-1 ) ;
        end
    end
    if ~found 
    end
end
fprintf( fid, '[DataHolder]\n');
fprintf( fid, 'time_index=5\n');
fprintf( fid, 'N_data_items=2000\n');
fprintf( fid, 'dt=0.05\n');
fprintf( fid, '[MainWindow]\n');
fprintf( fid, 'window_xpos=10\n');
fprintf( fid, 'window_ypos=10\n');
fprintf( fid, 'window_width=500\n');
fprintf( fid, 'window_height=500\n');
fprintf( fid, '[Connection]\n');
fprintf( fid, 'hostname=localhost\n');
fprintf( fid, 'port_number=3000\n');
fprintf( fid, 'timeout=60\n');
fprintf( fid, '[GraphWindows]\n');
fclose(fid);


% Select a limited signal list for GH Bladed

% Allowed values for Units Meaning (strict SI) 
% -         (No units specified) 
% 1/T       s-1 (Hz) 
% A         rad 
% A/P       rad/W 
% A/PT      rad/Ws 
% A/PTT     rad/Ws² 
% A/T       rad/s 
% A/TT      rad/s² 
% F         N 
% F/L       N/m 
% F/LL      N/m² 
% FL        Nm 
% FL/A      Nm/rad 
% FL/L      Nm/m 
% FLL       Nm² 
% FLT/A     Nms/rad 
% FLTT/AA   Nms²/rad² 
% I         A 
% L         m 
% L/T       m/s 
% L/TT      m/s² 
% LLL       m³    
% LLL/A     m³/rad 
% M         kg 
% M/L       kg/m 
% M/LLL     kg/m³ 
% M/LT      kg/ms 
% MLL       kgm² 
% N         (No units specified) 
% P         W 
% PT        J 
% Q         VAr 
% T         s 
% V         V 
% VI        VA


none    = ':-;'     ;
rad     = ':A;'     ;
rads    = ':A/T;'   ;
radss   = ':A/TT;'  ;
nm      = ':FL;'    ;
m       = ':L;'     ;
ms      = ':L/T;'   ;
time    = ':T;'     ;
inertia = ':MLL;'   ;

list = {

    VERSION                     , none  ; ...
    'BASE_SPD_RTSP'             , rads  ; ...
    'BASE_SPD_RTSP_P_LPF'       , rad   ; ...
    'BASE_SPD_RTSP_T_LPF'       , rad   ; ...
    'BASE_SPD_TORQ_SETPOINT'    , rads  ; ...
    'BASE_SPD_PIT_MIN'          , rad   ; ...
    'BASE_SPD_PIT_MAX'          , rad   ; ...
    'BASE_SPD_PIT_MIN_SPD'      , rads  ; ...
    'BASE_SPD_PIT_MAX_SPD'      , rads  ; ...
    'BASE_SPD_PIT_SETPOINT'     , rads  ; ...
    'BASE_SPD_DEM_TORQ'         , nm    ; ...
    'BASE_SPD_DEM_PITCH'        , rad   ; ...
    'BASE_DTD_OMR'              , rads  ; ...
    'BASE_DTD_OMR_LPF'          , rads  ; ...
    'BASE_DTD_DEM_TORQ'         , nm    ; ...
    'BASE_SWD_SIDEWACC'         , ms    ; ...
    'BASE_SWD_SIDEWACC_LPF'     , ms    ; ...
    'BASE_SWD_DEM_TORQ'         , nm    ; ...
    'BASE_FAD_FOREAFTACC'       , ms    ; ...
    'BASE_FAD_FOREAFTACC_LPF'   , ms    ; ...
    'BASE_FAD_DEM_PIT'          , rad   ; ...
    'BASE_IPC1P_D_MIN'          , rad   ; ...
    'BASE_IPC1P_D_MAX'          , rad   ; ...
    'BASE_IPC1P_D_DEM_PIT'      , rad   ; ...
    'BASE_IPC1P_Q_MIN'          , rad   ; ...
    'BASE_IPC1P_Q_MAX'          , rad   ; ...
    'BASE_IPC1P_Q_DEM_PIT'      , rad   ; ...
    'BASE_IPC1P_DEM_PIT1'       , rad   ; ...
    'BASE_IPC1P_DEM_PIT2'       , rad   ; ...
    'BASE_YAW_DEMYAWMOMENT'     , nm    ; ...  
    'BASE_YAWIPC_ERR'           , rad   ; ...    
    'BASE_YAWIPC_ERR_LPF'       , rad   ; ...    
    'BASE_YAWIPC_MAX'           , rad   ; ...    
    'BASE_YAWIPC_MIN'           , rad   ; ...    
    'BASE_YAWIPC_RATEMAX'       , rads  ;  ...    
    'BASE_YAWIPC_RATEMIN'       , rads  ;  ...    
    'BASE_YAWIPC_KP'            , none  ;  ...    
    'BASE_YAWIPC_KI'            , none  ;  ...    
    'BASE_YAWIPC_KD'            , none  ;  ...      
    'BASE_YAW_SETPOINT'         , rad   ;  ...    
    'BASE_YAW_MODE'             , none  ;  ...    
    'BASE_YAW_DEMYAWRATE'       , rads  ; ...    
    'BASE_YAW_DEMYAWMOMENT'     , nm    ; ...
    'OPER_DEM_YAWRATE'          , rads  ; ...
    'SUP_TRIGGER'               , none  ; ...
    'SUP_TRIGGER_INDEX'         , none  ; ...
    'SUP_STATE'                 , none  ; ...
    'SUP_STATE_INDEX'           , none  ; ...
    'EEC_EST_WIND_F'            , ms    ; ...
    'EEC_ECG_LSFITRES'          , none  ; ...
    'EEC_ECG_LEVEL'             , none  ; ...
    'EEC_EOG_LSFITRES'          , none  ; ...
    'EEC_EOG_LEVEL'             , none  ; ...
    'EEC_EOG50_LSFITRES'        , none  ; ...
    'EEC_EOG50_LEVEL'           , none    ...
    
};

fid = fopen( './../mcu/src/interface/bladedlogsignals.c', 'w' );

fprintf( fid, '/* Automatically generated file */\n\n');

fprintf( fid, '#include <string.h>\n\n');
fprintf( fid, '#include "./../signals/signal_definitions_internal.h"\n');
fprintf( fid, '#include "./../signals/signal_definitions_external.h"\n');
fprintf( fid, '#include "./../maincontrollerunit.h"\n');
fprintf( fid, '#include "./bladedwrapper.h"\n\n');


fprintf( fid, 'int bladedlogsignals ( float * pBladedData, char * cOutName, const REAL * pLogdata, const int iLogIndex, const int iLogNrVariables  ) { \n\n');

fprintf( fid, '    pBladedData[ iLogIndex + %3d ] = 0.0; \n', 0 );

for k = 2:length(list)
    found = 0;
    for j = 1:length(master)
        if strcmp( list{k} , master{j} )
            found = 1;
            fprintf(fid, '    pBladedData[ iLogIndex + %3d ] = (float)pLogdata[ %s ]; \n', k-1, list{k,1} );
        end
    end
    if ~found 
    
    end
end

fprintf( fid, '\n    pBladedData[ iLogNrVariables ] = %1.3f;\n\n', k);

fprintf( fid, '\n\n    strcpy( cOutName, "" );\n');
fprintf(fid, '    strcat( cOutName, "%s%s" );\n', list{1,1}, list{1,2} );

for k = 2:length(list)
    found = 0;
    for j = 1:length(master)
        if strcmp( list{k} , master{j} )
            found = 1;
            fprintf(fid, '    strcat( cOutName, "%s%s" );\n', list{k,1}, list{k,2} );
        end
    end
    if ~found 
    
    end
end
fprintf( fid, '\n\n    return 0;');
fprintf( fid, '\n\n}');

 